CREATE SCHEMA airline_project;
USE airline_project;
CREATE TABLE airlines_raw (
    IATA_CODE STRING,
    AIRLINE STRING
);

CREATE TABLE airports_raw (
    IATA_CODE STRING,
    AIRPORT STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    LATITUDE STRING,
    LONGITUDE STRING
);

CREATE TABLE flights_raw (
    YEAR STRING,
    MONTH STRING,
    DAY STRING,
    DAY_OF_WEEK STRING,
    AIRLINE STRING,
    FLIGHT_NUMBER STRING,
    TAIL_NUMBER STRING,
    ORIGIN_AIRPORT STRING,
    DESTINATION_AIRPORT STRING,
    SCHEDULED_DEPARTURE STRING,
    DEPARTURE_TIME STRING,
    DEPARTURE_DELAY STRING,
    TAXI_OUT STRING,
    WHEELS_OFF STRING,
    SCHEDULED_TIME STRING,
    ELAPSED_TIME STRING,
    AIR_TIME STRING,
    DISTANCE STRING,
    WHEELS_ON STRING,
    TAXI_IN STRING,
    SCHEDULED_ARRIVAL STRING,
    ARRIVAL_TIME STRING,
    ARRIVAL_DELAY STRING,
    DIVERTED STRING,
    CANCELLED STRING,
    CANCELLATION_REASON STRING,
    AIR_SYSTEM_DELAY STRING,
    SECURITY_DELAY STRING,
    AIRLINE_DELAY STRING,
    LATE_AIRCRAFT_DELAY STRING,
    WEATHER_DELAY STRING,
    SCHEDULED_DEPARTURE_STR STRING,
    DEPARTURE_TIME_STR STRING,
    WHEELS_OFF_STR STRING,
    WHEELS_ON_STR STRING,
    SCHEDULED_ARRIVAL_STR STRING,
    ARRIVAL_TIME_STR STRING,
    AIRLINE_FULL_NAME STRING,
    ORIGIN_AIRPORT_NAME STRING,
    ORIGIN_CITY STRING,
    ORIGIN_STATE STRING,
    COUNTRY_x STRING,
    ORIGIN_LAT STRING,
    ORIGIN_LON STRING,
    DESTINATION_AIRPORT_NAME STRING,
    DESTINATION_CITY STRING,
    DESTINATION_STATE STRING,
    COUNTRY_y STRING,
    DESTINATION_LAT STRING,
    DESTINATION_LON STRING
);

--AIRLINES
COPY INTO airlines_raw
FROM '/Volumes/workspace/default/data/airlines.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS ('header' = 'true');

--AIRPORTS
COPY INTO airports_raw
FROM '/Volumes/workspace/default/data/airports.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS ('header' = 'true');

--FLIGHTS
COPY INTO flights_raw
FROM '/Volumes/workspace/default/data/flights_CLEANED_ENRICHED.csv'
FILEFORMAT = CSV
FORMAT_OPTIONS ('header' = 'true');

--Check the loaded tables
USE airline_project;

SELECT COUNT(*) AS flights_rows FROM flights_raw;
SELECT COUNT(*) AS airlines_rows FROM airlines_raw;
SELECT COUNT(*) AS airports_rows FROM airports_raw;

SELECT * FROM flights_raw LIMIT 5;
SELECT * FROM airlines_raw LIMIT 5;
SELECT * FROM airports_raw LIMIT 5;

--airlines_clean
CREATE OR REPLACE TABLE airlines_clean AS
SELECT
    TRIM(IATA_CODE) AS IATA_CODE,
    TRIM(AIRLINE) AS AIRLINE_NAME
FROM airlines_raw;

--airports_clean
CREATE OR REPLACE TABLE airports_clean AS
SELECT
    TRIM(IATA_CODE) AS IATA_CODE,
    TRIM(AIRPORT) AS AIRPORT_NAME,
    TRIM(CITY) AS CITY,
    TRIM(STATE) AS STATE,
    TRIM(COUNTRY) AS COUNTRY,
    CAST(NULLIF(TRIM(LATITUDE), '') AS DOUBLE) AS LATITUDE,
    CAST(NULLIF(TRIM(LONGITUDE), '') AS DOUBLE) AS LONGITUDE
FROM airports_raw;

--flights_clean
CREATE OR REPLACE TABLE flights_clean AS
SELECT
    CAST(NULLIF(TRIM(YEAR), '') AS INT) AS YEAR,
    CAST(NULLIF(TRIM(MONTH), '') AS INT) AS MONTH,
    CAST(NULLIF(TRIM(DAY), '') AS INT) AS DAY,
    CAST(NULLIF(TRIM(DAY_OF_WEEK), '') AS INT) AS DAY_OF_WEEK,
    TRIM(AIRLINE) AS AIRLINE,
    CAST(NULLIF(TRIM(FLIGHT_NUMBER), '') AS INT) AS FLIGHT_NUMBER,
    TRIM(TAIL_NUMBER) AS TAIL_NUMBER,
    TRIM(ORIGIN_AIRPORT) AS ORIGIN_AIRPORT,
    TRIM(DESTINATION_AIRPORT) AS DESTINATION_AIRPORT,
    CAST(NULLIF(TRIM(SCHEDULED_DEPARTURE), '') AS INT) AS SCHEDULED_DEPARTURE,
    CAST(NULLIF(TRIM(DEPARTURE_TIME), '') AS INT) AS DEPARTURE_TIME,
    CAST(NULLIF(TRIM(DEPARTURE_DELAY), '') AS DOUBLE) AS DEPARTURE_DELAY,
    CAST(NULLIF(TRIM(TAXI_OUT), '') AS DOUBLE) AS TAXI_OUT,
    CAST(NULLIF(TRIM(WHEELS_OFF), '') AS INT) AS WHEELS_OFF,
    CAST(NULLIF(TRIM(SCHEDULED_TIME), '') AS DOUBLE) AS SCHEDULED_TIME,
    CAST(NULLIF(TRIM(ELAPSED_TIME), '') AS DOUBLE) AS ELAPSED_TIME,
    CAST(NULLIF(TRIM(AIR_TIME), '') AS DOUBLE) AS AIR_TIME,
    CAST(NULLIF(TRIM(DISTANCE), '') AS DOUBLE) AS DISTANCE,
    CAST(NULLIF(TRIM(WHEELS_ON), '') AS INT) AS WHEELS_ON,
    CAST(NULLIF(TRIM(TAXI_IN), '') AS DOUBLE) AS TAXI_IN,
    CAST(NULLIF(TRIM(SCHEDULED_ARRIVAL), '') AS INT) AS SCHEDULED_ARRIVAL,
    CAST(NULLIF(TRIM(ARRIVAL_TIME), '') AS INT) AS ARRIVAL_TIME,
    CAST(NULLIF(TRIM(ARRIVAL_DELAY), '') AS DOUBLE) AS ARRIVAL_DELAY,
    CAST(NULLIF(TRIM(DIVERTED), '') AS INT) AS DIVERTED,
    CAST(NULLIF(TRIM(CANCELLED), '') AS INT) AS CANCELLED,
    TRIM(CANCELLATION_REASON) AS CANCELLATION_REASON,
    CAST(NULLIF(TRIM(AIR_SYSTEM_DELAY), '') AS DOUBLE) AS AIR_SYSTEM_DELAY,
    CAST(NULLIF(TRIM(SECURITY_DELAY), '') AS DOUBLE) AS SECURITY_DELAY,
    CAST(NULLIF(TRIM(AIRLINE_DELAY), '') AS DOUBLE) AS AIRLINE_DELAY,
    CAST(NULLIF(TRIM(LATE_AIRCRAFT_DELAY), '') AS DOUBLE) AS LATE_AIRCRAFT_DELAY,
    CAST(NULLIF(TRIM(WEATHER_DELAY), '') AS DOUBLE) AS WEATHER_DELAY,
    TRIM(SCHEDULED_DEPARTURE_STR) AS SCHEDULED_DEPARTURE_STR,
    TRIM(DEPARTURE_TIME_STR) AS DEPARTURE_TIME_STR,
    TRIM(WHEELS_OFF_STR) AS WHEELS_OFF_STR,
    TRIM(WHEELS_ON_STR) AS WHEELS_ON_STR,
    TRIM(SCHEDULED_ARRIVAL_STR) AS SCHEDULED_ARRIVAL_STR,
    TRIM(ARRIVAL_TIME_STR) AS ARRIVAL_TIME_STR,
    TRIM(AIRLINE_FULL_NAME) AS AIRLINE_FULL_NAME,
    TRIM(ORIGIN_AIRPORT_NAME) AS ORIGIN_AIRPORT_NAME,
    TRIM(ORIGIN_CITY) AS ORIGIN_CITY,
    TRIM(ORIGIN_STATE) AS ORIGIN_STATE,
    TRIM(COUNTRY_x) AS COUNTRY_x,
    CAST(NULLIF(TRIM(ORIGIN_LAT), '') AS DOUBLE) AS ORIGIN_LAT,
    CAST(NULLIF(TRIM(ORIGIN_LON), '') AS DOUBLE) AS ORIGIN_LON,
    TRIM(DESTINATION_AIRPORT_NAME) AS DESTINATION_AIRPORT_NAME,
    TRIM(DESTINATION_CITY) AS DESTINATION_CITY,
    TRIM(DESTINATION_STATE) AS DESTINATION_STATE,
    TRIM(COUNTRY_y) AS COUNTRY_y,
    CAST(NULLIF(TRIM(DESTINATION_LAT), '') AS DOUBLE) AS DESTINATION_LAT,
    CAST(NULLIF(TRIM(DESTINATION_LON), '') AS DOUBLE) AS DESTINATION_LON
FROM flights_raw;

--final analysis table
CREATE OR REPLACE TABLE flight_analysis AS
SELECT
    f.*,
    COALESCE(f.AIRLINE_FULL_NAME, a.AIRLINE_NAME) AS FINAL_AIRLINE_NAME,

    CONCAT(f.ORIGIN_AIRPORT, '-', f.DESTINATION_AIRPORT) AS ROUTE,

    MAKE_DATE(f.YEAR, f.MONTH, f.DAY) AS FLIGHT_DATE,

    CASE WHEN f.ARRIVAL_DELAY > 0 THEN 1 ELSE 0 END AS ARR_DELAY_FLAG,
    CASE WHEN f.ARRIVAL_DELAY >= 15 THEN 1 ELSE 0 END AS ARR_DELAY_15_FLAG,
    CASE WHEN f.DEPARTURE_DELAY > 0 THEN 1 ELSE 0 END AS DEP_DELAY_FLAG,

    CASE
        WHEN f.SCHEDULED_DEPARTURE BETWEEN 0 AND 559 THEN 'Night'
        WHEN f.SCHEDULED_DEPARTURE BETWEEN 600 AND 1159 THEN 'Morning'
        WHEN f.SCHEDULED_DEPARTURE BETWEEN 1200 AND 1759 THEN 'Afternoon'
        ELSE 'Evening'
    END AS DEPARTURE_TIME_BAND,

    CASE
        WHEN f.DISTANCE < 500 THEN 'Short Haul'
        WHEN f.DISTANCE BETWEEN 500 AND 1500 THEN 'Medium Haul'
        ELSE 'Long Haul'
    END AS DISTANCE_BAND
FROM flights_clean f
LEFT JOIN airlines_clean a
    ON f.AIRLINE = a.IATA_CODE;

SELECT * FROM flight_analysis LIMIT 10;  

--A. Which airlines have the highest delays?
SELECT
    FINAL_AIRLINE_NAME AS AIRLINE,
    COUNT(*) AS TOTAL_FLIGHTS,
    ROUND(AVG(ARRIVAL_DELAY), 2) AS AVG_ARRIVAL_DELAY,
    ROUND(AVG(DEPARTURE_DELAY), 2) AS AVG_DEPARTURE_DELAY,
    SUM(ARR_DELAY_15_FLAG) AS DELAYED_15_PLUS,
    ROUND(100.0 * SUM(ARR_DELAY_15_FLAG) / COUNT(*), 2) AS DELAY_RATE_PCT
FROM flight_analysis
GROUP BY FINAL_AIRLINE_NAME
ORDER BY DELAY_RATE_PCT DESC, AVG_ARRIVAL_DELAY DESC;

--B. Which airports have the highest delay severity?
SELECT
    ORIGIN_AIRPORT,
    ORIGIN_AIRPORT_NAME,
    ORIGIN_CITY,
    ORIGIN_STATE,
    COUNT(*) AS TOTAL_FLIGHTS,
    ROUND(AVG(ARRIVAL_DELAY), 2) AS AVG_ARRIVAL_DELAY,
    ROUND(AVG(DEPARTURE_DELAY), 2) AS AVG_DEPARTURE_DELAY,
    ROUND(100.0 * SUM(ARR_DELAY_15_FLAG) / COUNT(*), 2) AS DELAY_RATE_PCT
FROM flight_analysis
GROUP BY ORIGIN_AIRPORT, ORIGIN_AIRPORT_NAME, ORIGIN_CITY, ORIGIN_STATE
ORDER BY AVG_ARRIVAL_DELAY DESC;

--C. Which routes are most associated with delays?
SELECT
    ROUTE,
    COUNT(*) AS TOTAL_FLIGHTS,
    ROUND(AVG(ARRIVAL_DELAY), 2) AS AVG_ARRIVAL_DELAY,
    ROUND(AVG(DEPARTURE_DELAY), 2) AS AVG_DEPARTURE_DELAY,
    ROUND(100.0 * SUM(ARR_DELAY_15_FLAG) / COUNT(*), 2) AS DELAY_RATE_PCT
FROM flight_analysis
GROUP BY ROUTE
HAVING COUNT(*) >= 50
ORDER BY DELAY_RATE_PCT DESC, AVG_ARRIVAL_DELAY DESC;

--D. Which operational factors affect delays?
SELECT
    DEPARTURE_TIME_BAND,
    DISTANCE_BAND,
    DAY_OF_WEEK,
    COUNT(*) AS TOTAL_FLIGHTS,
    ROUND(AVG(ARRIVAL_DELAY), 2) AS AVG_ARRIVAL_DELAY,
    ROUND(AVG(DEPARTURE_DELAY), 2) AS AVG_DEPARTURE_DELAY,
    ROUND(100.0 * SUM(CANCELLED) / COUNT(*), 2) AS CANCELLATION_RATE_PCT
FROM flight_analysis
GROUP BY DEPARTURE_TIME_BAND, DISTANCE_BAND, DAY_OF_WEEK
ORDER BY AVG_ARRIVAL_DELAY DESC;

-- Summary Tables
-- airline_summary
CREATE OR REPLACE TABLE airline_summary AS
SELECT
    FINAL_AIRLINE_NAME AS AIRLINE,
    COUNT(*) AS TOTAL_FLIGHTS,
    ROUND(AVG(ARRIVAL_DELAY), 2) AS AVG_ARR_DELAY,
    ROUND(AVG(DEPARTURE_DELAY), 2) AS AVG_DEP_DELAY,
    ROUND(100.0 * SUM(ARR_DELAY_15_FLAG) / COUNT(*), 2) AS DELAY_RATE_PCT,
    ROUND(100.0 * SUM(CANCELLED) / COUNT(*), 2) AS CANCELLATION_RATE_PCT
FROM flight_analysis
GROUP BY FINAL_AIRLINE_NAME;

--airport_summary
CREATE OR REPLACE TABLE airport_summary AS
SELECT
    ORIGIN_AIRPORT,
    ORIGIN_AIRPORT_NAME,
    ORIGIN_CITY,
    ORIGIN_STATE,
    COUNT(*) AS TOTAL_FLIGHTS,
    ROUND(AVG(ARRIVAL_DELAY), 2) AS AVG_ARR_DELAY,
    ROUND(AVG(DEPARTURE_DELAY), 2) AS AVG_DEP_DELAY,
    ROUND(100.0 * SUM(ARR_DELAY_15_FLAG) / COUNT(*), 2) AS DELAY_RATE_PCT,
    ROUND(100.0 * SUM(CANCELLED) / COUNT(*), 2) AS CANCELLATION_RATE_PCT
FROM flight_analysis
GROUP BY ORIGIN_AIRPORT, ORIGIN_AIRPORT_NAME, ORIGIN_CITY, ORIGIN_STATE;

--route_summary
CREATE OR REPLACE TABLE route_summary AS
SELECT
    ROUTE,
    ORIGIN_AIRPORT,
    DESTINATION_AIRPORT,
    DISTANCE_BAND,
    COUNT(*) AS TOTAL_FLIGHTS,
    ROUND(AVG(ARRIVAL_DELAY), 2) AS AVG_ARR_DELAY,
    ROUND(AVG(DEPARTURE_DELAY), 2) AS AVG_DEP_DELAY,
    ROUND(100.0 * SUM(ARR_DELAY_15_FLAG) / COUNT(*), 2) AS DELAY_RATE_PCT,
    ROUND(100.0 * SUM(CANCELLED) / COUNT(*), 2) AS CANCELLATION_RATE_PCT
FROM flight_analysis
GROUP BY ROUTE, ORIGIN_AIRPORT, DESTINATION_AIRPORT, DISTANCE_BAND;

SELECT * 
FROM airline_project.airline_summary
LIMIT 10;

SELECT * 
FROM airline_project.route_summary
LIMIT 10;

SELECT * 
FROM airline_project.airport_summary
LIMIT 10;